workflows:
  my-flutter-workflow:
    name: Build Android APK
    working_directory: photovault_flutter  # <--- YE LINE YAHAN ADD KAREIN
    instance_type: mac_mini_m1
    max_build_duration: 120
    environment:
      flutter: stable
    scripts:
      - name: Get Flutter Packages
        script: flutter pub get
      - name: Build Android APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
