#!/usr/bin/env python3
"""
PhotoVault - Firebase Setup & Management Script
================================================
This script helps you:
1. Generate firebase-config.js with your credentials
2. Generate Firestore security rules
3. Generate Storage security rules
4. Validate your Firebase config
5. Deploy to Vercel (if CLI installed)

Usage:
    python setup_firebase.py
    python setup_firebase.py --generate-config
    python setup_firebase.py --generate-rules
    python setup_firebase.py --deploy
    python setup_firebase.py --validate
"""

import json
import os
import sys
import subprocess
import re
from pathlib import Path


# ============================================================
# COLORS FOR TERMINAL OUTPUT
# ============================================================
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'


def print_banner():
    """Print the PhotoVault banner."""
    print(f"""
{Colors.CYAN}{Colors.BOLD}
╔══════════════════════════════════════════════════╗
║          📸 PhotoVault Setup Wizard             ║
║     Firebase Config & Vercel Deployment         ║
╚══════════════════════════════════════════════════╝
{Colors.END}""")


def print_success(msg):
    print(f"{Colors.GREEN}✅ {msg}{Colors.END}")


def print_error(msg):
    print(f"{Colors.RED}❌ {msg}{Colors.END}")


def print_info(msg):
    print(f"{Colors.BLUE}ℹ️  {msg}{Colors.END}")


def print_warning(msg):
    print(f"{Colors.WARNING}⚠️  {msg}{Colors.END}")


# ============================================================
# FIREBASE CONFIG GENERATOR
# ============================================================
def generate_firebase_config():
    """Interactive prompt to generate firebase-config.js"""
    print(f"\n{Colors.BOLD}📋 Firebase Configuration Generator{Colors.END}")
    print("=" * 50)
    print_info("Get these values from Firebase Console > Project Settings > Your Web App")
    print()

    api_key = input(f"{Colors.CYAN}Enter API Key: {Colors.END}").strip()
    auth_domain = input(f"{Colors.CYAN}Enter Auth Domain (e.g., myapp.firebaseapp.com): {Colors.END}").strip()
    project_id = input(f"{Colors.CYAN}Enter Project ID: {Colors.END}").strip()
    storage_bucket = input(f"{Colors.CYAN}Enter Storage Bucket (e.g., myapp.appspot.com): {Colors.END}").strip()
    messaging_sender_id = input(f"{Colors.CYAN}Enter Messaging Sender ID: {Colors.END}").strip()
    app_id = input(f"{Colors.CYAN}Enter App ID: {Colors.END}").strip()

    if not all([api_key, auth_domain, project_id, storage_bucket, messaging_sender_id, app_id]):
        print_error("All fields are required! Please try again.")
        return False

    config_content = f'''// ============================================================
// Firebase Configuration - PhotoVault
// ============================================================
// Auto-generated by setup_firebase.py
// ============================================================

import {{ initializeApp }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import {{ getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {{ getFirestore, collection, addDoc, getDocs, deleteDoc, updateDoc, doc, query, where, orderBy, serverTimestamp }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";
import {{ getStorage, ref, uploadBytesResumable, getDownloadURL, deleteObject }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-storage.js";

const firebaseConfig = {{
    apiKey: "{api_key}",
    authDomain: "{auth_domain}",
    projectId: "{project_id}",
    storageBucket: "{storage_bucket}",
    messagingSenderId: "{messaging_sender_id}",
    appId: "{app_id}"
}};

// Initialize Firebase
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);
const storage = getStorage(app);

// Export services and functions for app.js
window.firebaseServices = {{ auth, db, storage }};
window.firebaseAuth = {{ createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged }};
window.firebaseFirestore = {{ collection, addDoc, getDocs, deleteDoc, updateDoc, doc, query, where, orderBy, serverTimestamp }};
window.firebaseStorage = {{ ref, uploadBytesResumable, getDownloadURL, deleteObject }};
'''

    config_path = Path("js/firebase-config.js")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content)

    print()
    print_success(f"Firebase config written to: {config_path}")
    print_info(f"Project ID: {project_id}")
    return True


# ============================================================
# SECURITY RULES GENERATOR
# ============================================================
def generate_firestore_rules():
    """Generate Firestore security rules file."""
    rules = '''rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    // Media collection - users can only access their own photos
    match /media/{document} {
      allow read: if request.auth != null && resource.data.userId == request.auth.uid;
      allow create: if request.auth != null && request.resource.data.userId == request.auth.uid;
      allow update, delete: if request.auth != null && resource.data.userId == request.auth.uid;
    }

    // Folders collection - users can only access their own albums
    match /folders/{document} {
      allow read: if request.auth != null && resource.data.userId == request.auth.uid;
      allow create: if request.auth != null && request.resource.data.userId == request.auth.uid;
      allow update, delete: if request.auth != null && resource.data.userId == request.auth.uid;
    }
  }
}
'''
    rules_path = Path("firestore.rules")
    rules_path.write_text(rules)
    print_success(f"Firestore rules written to: {rules_path}")
    return rules_path


def generate_storage_rules():
    """Generate Firebase Storage security rules file."""
    rules = '''rules_version = '2';
service firebase.storage {
  match /b/{bucket}/o {
    // Users can only read/write to their own folder
    match /users/{userId}/{allPaths=**} {
      allow read, write: if request.auth != null && request.auth.uid == userId;
    }
  }
}
'''
    rules_path = Path("storage.rules")
    rules_path.write_text(rules)
    print_success(f"Storage rules written to: {rules_path}")
    return rules_path


def generate_all_rules():
    """Generate both Firestore and Storage rules."""
    print(f"\n{Colors.BOLD}🔐 Security Rules Generator{Colors.END}")
    print("=" * 50)
    generate_firestore_rules()
    generate_storage_rules()
    print()
    print_info("Copy these rules to Firebase Console:")
    print(f"  • Firestore: Firebase Console > Firestore > Rules")
    print(f"  • Storage:   Firebase Console > Storage > Rules")


# ============================================================
# CONFIG VALIDATOR
# ============================================================
def validate_config():
    """Validate the current firebase-config.js file."""
    print(f"\n{Colors.BOLD}🔍 Config Validator{Colors.END}")
    print("=" * 50)

    config_path = Path("js/firebase-config.js")
    if not config_path.exists():
        print_error("js/firebase-config.js not found!")
        print_info("Run: python setup_firebase.py --generate-config")
        return False

    content = config_path.read_text()

    # Check for placeholder values
    placeholders = ["YOUR_API_KEY", "YOUR_PROJECT_ID", "YOUR_MESSAGING_SENDER_ID", "YOUR_APP_ID"]
    has_placeholders = False

    for placeholder in placeholders:
        if placeholder in content:
            print_error(f"Found placeholder: {placeholder}")
            has_placeholders = True

    if has_placeholders:
        print()
        print_warning("Config still has placeholder values!")
        print_info("Run: python setup_firebase.py --generate-config")
        return False

    # Validate format
    api_key_match = re.search(r'apiKey:\s*"(.+?)"', content)
    project_id_match = re.search(r'projectId:\s*"(.+?)"', content)

    if api_key_match and project_id_match:
        print_success("Config format is valid")
        print_info(f"Project ID: {project_id_match.group(1)}")
        print_info(f"API Key: {api_key_match.group(1)[:10]}...")
        return True
    else:
        print_error("Could not parse config values")
        return False


# ============================================================
# VERCEL DEPLOYMENT
# ============================================================
def check_vercel_cli():
    """Check if Vercel CLI is installed."""
    try:
        result = subprocess.run(["vercel", "--version"], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False


def deploy_to_vercel(production=False):
    """Deploy the app to Vercel."""
    print(f"\n{Colors.BOLD}🚀 Vercel Deployment{Colors.END}")
    print("=" * 50)

    if not check_vercel_cli():
        print_error("Vercel CLI not found!")
        print()
        print_info("Install Vercel CLI:")
        print(f"  {Colors.CYAN}npm install -g vercel{Colors.END}")
        print()
        print_info("Or deploy manually:")
        print(f"  1. Go to {Colors.CYAN}https://vercel.com/new{Colors.END}")
        print(f"  2. Import your GitHub repo: {Colors.CYAN}AAKASH-CODES-CODE/Photos{Colors.END}")
        print(f"  3. Framework Preset: {Colors.CYAN}Other{Colors.END}")
        print(f"  4. Root Directory: {Colors.CYAN}./{Colors.END}")
        print(f"  5. Click {Colors.GREEN}Deploy{Colors.END}")
        return False

    # Validate config first
    if not validate_config():
        print()
        print_warning("Fix your Firebase config before deploying!")
        response = input(f"{Colors.CYAN}Deploy anyway? (y/N): {Colors.END}").strip().lower()
        if response != 'y':
            return False

    cmd = ["vercel", "--prod"] if production else ["vercel"]
    mode = "Production" if production else "Preview"

    print_info(f"Deploying to Vercel ({mode})...")
    print()

    try:
        result = subprocess.run(cmd, capture_output=False)
        if result.returncode == 0:
            print()
            print_success(f"Deployed to Vercel ({mode})!")
            return True
        else:
            print_error("Deployment failed. Check the errors above.")
            return False
    except Exception as e:
        print_error(f"Error: {e}")
        return False


# ============================================================
# FULL SETUP WIZARD
# ============================================================
def full_setup():
    """Run the complete setup wizard."""
    print_banner()

    print(f"{Colors.BOLD}What would you like to do?{Colors.END}")
    print()
    print("  1. 🔧 Generate Firebase Config (interactive)")
    print("  2. 🔐 Generate Security Rules")
    print("  3. ✅ Validate Current Config")
    print("  4. 🚀 Deploy to Vercel (Preview)")
    print("  5. 🌐 Deploy to Vercel (Production)")
    print("  6. 📦 Full Setup (Config + Rules + Deploy)")
    print("  7. ❌ Exit")
    print()

    choice = input(f"{Colors.CYAN}Enter your choice (1-7): {Colors.END}").strip()

    if choice == "1":
        generate_firebase_config()
    elif choice == "2":
        generate_all_rules()
    elif choice == "3":
        validate_config()
    elif choice == "4":
        deploy_to_vercel(production=False)
    elif choice == "5":
        deploy_to_vercel(production=True)
    elif choice == "6":
        print_info("Starting full setup...")
        if generate_firebase_config():
            generate_all_rules()
            print()
            response = input(f"{Colors.CYAN}Deploy to Vercel now? (y/N): {Colors.END}").strip().lower()
            if response == 'y':
                deploy_to_vercel(production=True)
    elif choice == "7":
        print_info("Goodbye!")
        sys.exit(0)
    else:
        print_error("Invalid choice. Please enter 1-7.")


# ============================================================
# CLI ARGUMENTS
# ============================================================
def main():
    """Main entry point with CLI argument support."""
    if len(sys.argv) > 1:
        arg = sys.argv[1]

        if arg in ("--generate-config", "-c"):
            print_banner()
            generate_firebase_config()
        elif arg in ("--generate-rules", "-r"):
            print_banner()
            generate_all_rules()
        elif arg in ("--validate", "-v"):
            print_banner()
            validate_config()
        elif arg in ("--deploy", "-d"):
            print_banner()
            deploy_to_vercel(production=True)
        elif arg in ("--deploy-preview", "-p"):
            print_banner()
            deploy_to_vercel(production=False)
        elif arg in ("--help", "-h"):
            print_banner()
            print(f"{Colors.BOLD}Available Commands:{Colors.END}")
            print()
            print(f"  {Colors.CYAN}python setup_firebase.py{Colors.END}              Interactive wizard")
            print(f"  {Colors.CYAN}python setup_firebase.py --generate-config{Colors.END}  Generate Firebase config")
            print(f"  {Colors.CYAN}python setup_firebase.py --generate-rules{Colors.END}   Generate security rules")
            print(f"  {Colors.CYAN}python setup_firebase.py --validate{Colors.END}         Validate config")
            print(f"  {Colors.CYAN}python setup_firebase.py --deploy{Colors.END}           Deploy to Vercel (prod)")
            print(f"  {Colors.CYAN}python setup_firebase.py --deploy-preview{Colors.END}   Deploy to Vercel (preview)")
            print()
            print(f"  {Colors.CYAN}Short flags: -c, -r, -v, -d, -p, -h{Colors.END}")
        else:
            print_error(f"Unknown argument: {arg}")
            print_info("Use --help for available commands")
    else:
        full_setup()


if __name__ == "__main__":
    main()
