#!/usr/bin/env python3
"""
PhotoVault - Setup & Deployment Wizard
=======================================
This script helps you:
1. Generate firebase-config.js with Firebase + Cloudinary credentials
2. Generate Firestore security rules
3. Validate your config
4. Deploy to Vercel

Usage:
    python setup_firebase.py
    python setup_firebase.py --generate-config
    python setup_firebase.py --generate-rules
    python setup_firebase.py --deploy
    python setup_firebase.py --validate
"""

import json
import os
import sys
import subprocess
import re
from pathlib import Path


# ============================================================
# COLORS FOR TERMINAL OUTPUT
# ============================================================
class Colors:
    HEADER = '\033[95m'
    BLUE = '\033[94m'
    CYAN = '\033[96m'
    GREEN = '\033[92m'
    WARNING = '\033[93m'
    RED = '\033[91m'
    END = '\033[0m'
    BOLD = '\033[1m'


def print_banner():
    print(f"""
{Colors.CYAN}{Colors.BOLD}
╔══════════════════════════════════════════════════╗
║        📸 PhotoVault Setup Wizard               ║
║   Firebase + Cloudinary (100% FREE Setup)       ║
╚══════════════════════════════════════════════════╝
{Colors.END}""")


def print_success(msg):
    print(f"{Colors.GREEN}✅ {msg}{Colors.END}")


def print_error(msg):
    print(f"{Colors.RED}❌ {msg}{Colors.END}")


def print_info(msg):
    print(f"{Colors.BLUE}ℹ️  {msg}{Colors.END}")


def print_warning(msg):
    print(f"{Colors.WARNING}⚠️  {msg}{Colors.END}")


# ============================================================
# CONFIG GENERATOR (Firebase + Cloudinary)
# ============================================================
def generate_config():
    """Interactive prompt to generate firebase-config.js with Cloudinary"""
    print(f"\n{Colors.BOLD}📋 Configuration Generator (Firebase + Cloudinary){Colors.END}")
    print("=" * 55)

    # --- CLOUDINARY ---
    print(f"\n{Colors.CYAN}{Colors.BOLD}☁️  CLOUDINARY CONFIG (FREE - 25GB){Colors.END}")
    print(f"{Colors.BLUE}   Get from: https://cloudinary.com/console{Colors.END}")
    print()

    cloud_name = input(f"   {Colors.CYAN}Cloud Name: {Colors.END}").strip()
    upload_preset = input(f"   {Colors.CYAN}Upload Preset (Unsigned): {Colors.END}").strip()

    if not cloud_name or not upload_preset:
        print_error("Cloud Name and Upload Preset are required!")
        print()
        print_info("Cloudinary Upload Preset kaise banaye:")
        print(f"   1. {Colors.CYAN}cloudinary.com{Colors.END} pe login karo")
        print(f"   2. {Colors.CYAN}Settings > Upload > Upload Presets{Colors.END}")
        print(f"   3. {Colors.CYAN}Add Upload Preset{Colors.END} click karo")
        print(f"   4. Signing Mode: {Colors.GREEN}Unsigned{Colors.END}")
        print(f"   5. Save karo aur preset name copy karo")
        return False

    # --- FIREBASE ---
    print(f"\n{Colors.CYAN}{Colors.BOLD}🔥 FIREBASE CONFIG (FREE){Colors.END}")
    print(f"{Colors.BLUE}   Get from: Firebase Console > Project Settings > Your Web App{Colors.END}")
    print()

    api_key = input(f"   {Colors.CYAN}API Key: {Colors.END}").strip()
    project_id = input(f"   {Colors.CYAN}Project ID: {Colors.END}").strip()
    auth_domain = input(f"   {Colors.CYAN}Auth Domain [{project_id}.firebaseapp.com]: {Colors.END}").strip()
    if not auth_domain:
        auth_domain = f"{project_id}.firebaseapp.com"
    storage_bucket = input(f"   {Colors.CYAN}Storage Bucket [{project_id}.appspot.com]: {Colors.END}").strip()
    if not storage_bucket:
        storage_bucket = f"{project_id}.appspot.com"
    messaging_sender_id = input(f"   {Colors.CYAN}Messaging Sender ID: {Colors.END}").strip()
    app_id = input(f"   {Colors.CYAN}App ID: {Colors.END}").strip()

    if not all([api_key, project_id, messaging_sender_id, app_id]):
        print_error("All Firebase fields are required!")
        return False

    # --- WRITE CONFIG FILE ---
    config_content = f'''// ============================================================
// Firebase + Cloudinary Configuration - PhotoVault
// ============================================================
// Auto-generated by setup_firebase.py
// Firebase: Authentication + Firestore (FREE)
// Cloudinary: Image Storage (25GB FREE)
// ============================================================

import {{ initializeApp }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-app.js";
import {{ getAuth, createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-auth.js";
import {{ getFirestore, collection, addDoc, getDocs, deleteDoc, updateDoc, doc, query, where, orderBy, serverTimestamp }} from "https://www.gstatic.com/firebasejs/10.12.2/firebase-firestore.js";

const firebaseConfig = {{
    apiKey: "{api_key}",
    authDomain: "{auth_domain}",
    projectId: "{project_id}",
    storageBucket: "{storage_bucket}",
    messagingSenderId: "{messaging_sender_id}",
    appId: "{app_id}"
}};

const cloudinaryConfig = {{
    cloudName: "{cloud_name}",
    uploadPreset: "{upload_preset}"
}};

// Initialize Firebase (Auth + Firestore only — NO Storage needed!)
const app = initializeApp(firebaseConfig);
const auth = getAuth(app);
const db = getFirestore(app);

// Export services and functions for app.js
window.firebaseServices = {{ auth, db }};
window.cloudinaryConfig = cloudinaryConfig;
window.firebaseAuth = {{ createUserWithEmailAndPassword, signInWithEmailAndPassword, signOut, onAuthStateChanged }};
window.firebaseFirestore = {{ collection, addDoc, getDocs, deleteDoc, updateDoc, doc, query, where, orderBy, serverTimestamp }};
'''

    config_path = Path("js/firebase-config.js")
    config_path.parent.mkdir(parents=True, exist_ok=True)
    config_path.write_text(config_content)

    print()
    print_success(f"Config written to: {config_path}")
    print_info(f"Firebase Project: {project_id}")
    print_info(f"Cloudinary Cloud: {cloud_name}")
    print_info(f"Upload Preset: {upload_preset}")
    print()
    print(f"{Colors.GREEN}{Colors.BOLD}🎉 Config ready! Ab app chalane ke liye:{Colors.END}")
    print(f"   {Colors.CYAN}python -m http.server 8000{Colors.END}")
    print(f"   {Colors.CYAN}Open: http://localhost:8000{Colors.END}")
    return True


# ============================================================
# SECURITY RULES GENERATOR
# ============================================================
def generate_firestore_rules():
    """Generate Firestore security rules file."""
    rules = '''rules_version = '2';
service cloud.firestore {
  match /databases/{database}/documents {

    // Media collection - users can only access their own photos
    match /media/{document} {
      allow read: if request.auth != null && resource.data.userId == request.auth.uid;
      allow create: if request.auth != null && request.resource.data.userId == request.auth.uid;
      allow update, delete: if request.auth != null && resource.data.userId == request.auth.uid;
    }

    // Folders collection - users can only access their own albums
    match /folders/{document} {
      allow read: if request.auth != null && resource.data.userId == request.auth.uid;
      allow create: if request.auth != null && request.resource.data.userId == request.auth.uid;
      allow update, delete: if request.auth != null && resource.data.userId == request.auth.uid;
    }
  }
}
'''
    rules_path = Path("firestore.rules")
    rules_path.write_text(rules)
    print_success(f"Firestore rules written to: {rules_path}")
    return rules_path


def generate_all_rules():
    """Generate Firestore rules (no Storage rules needed with Cloudinary!)"""
    print(f"\n{Colors.BOLD}🔐 Security Rules Generator{Colors.END}")
    print("=" * 50)
    generate_firestore_rules()
    print()
    print_info("Firebase Storage rules ki zaroorat NAHI hai!")
    print_info("Hum Cloudinary use kar rahe hain (FREE 25GB)")
    print()
    print_info("Firestore rules paste karo:")
    print(f"   Firebase Console > Firestore > Rules > Publish")


# ============================================================
# CONFIG VALIDATOR
# ============================================================
def validate_config():
    """Validate the current firebase-config.js file."""
    print(f"\n{Colors.BOLD}🔍 Config Validator{Colors.END}")
    print("=" * 50)

    config_path = Path("js/firebase-config.js")
    if not config_path.exists():
        print_error("js/firebase-config.js not found!")
        print_info("Run: python setup_firebase.py --generate-config")
        return False

    content = config_path.read_text()
    errors = []

    # Check Firebase placeholders
    firebase_placeholders = ["YOUR_API_KEY", "YOUR_PROJECT_ID", "YOUR_MESSAGING_SENDER_ID", "YOUR_APP_ID"]
    for p in firebase_placeholders:
        if p in content:
            errors.append(f"Firebase placeholder found: {p}")

    # Check Cloudinary placeholders
    cloudinary_placeholders = ["YOUR_CLOUD_NAME", "YOUR_UPLOAD_PRESET"]
    for p in cloudinary_placeholders:
        if p in content:
            errors.append(f"Cloudinary placeholder found: {p}")

    if errors:
        for e in errors:
            print_error(e)
        print()
        print_warning("Config me placeholder values hain!")
        print_info("Run: python setup_firebase.py --generate-config")
        return False

    # Validate format
    cloud_name_match = re.search(r'cloudName:\s*"(.+?)"', content)
    project_id_match = re.search(r'projectId:\s*"(.+?)"', content)
    preset_match = re.search(r'uploadPreset:\s*"(.+?)"', content)

    if cloud_name_match and project_id_match and preset_match:
        print_success("Config format is valid!")
        print_info(f"Firebase Project: {project_id_match.group(1)}")
        print_info(f"Cloudinary Cloud: {cloud_name_match.group(1)}")
        print_info(f"Upload Preset: {preset_match.group(1)}")
        return True
    else:
        print_error("Could not parse all config values")
        return False


# ============================================================
# VERCEL DEPLOYMENT
# ============================================================
def check_vercel_cli():
    try:
        result = subprocess.run(["vercel", "--version"], capture_output=True, text=True)
        return result.returncode == 0
    except FileNotFoundError:
        return False


def deploy_to_vercel(production=False):
    """Deploy the app to Vercel."""
    print(f"\n{Colors.BOLD}🚀 Vercel Deployment{Colors.END}")
    print("=" * 50)

    if not check_vercel_cli():
        print_error("Vercel CLI not found!")
        print()
        print_info("Install karo:")
        print(f"   {Colors.CYAN}npm install -g vercel{Colors.END}")
        print()
        print_info("Ya manually deploy karo:")
        print(f"   1. {Colors.CYAN}https://vercel.com/new{Colors.END} pe jao")
        print(f"   2. GitHub repo import karo")
        print(f"   3. Framework: {Colors.CYAN}Other{Colors.END}")
        print(f"   4. {Colors.GREEN}Deploy{Colors.END} click karo")
        return False

    if not validate_config():
        print()
        response = input(f"{Colors.CYAN}Config incomplete hai. Phir bhi deploy kare? (y/N): {Colors.END}").strip().lower()
        if response != 'y':
            return False

    cmd = ["vercel", "--prod"] if production else ["vercel"]
    mode = "Production" if production else "Preview"

    print_info(f"Deploying ({mode})...")
    print()

    try:
        result = subprocess.run(cmd)
        if result.returncode == 0:
            print()
            print_success(f"Vercel deploy successful ({mode})! 🎉")
            return True
        else:
            print_error("Deployment failed.")
            return False
    except Exception as e:
        print_error(f"Error: {e}")
        return False


# ============================================================
# FULL SETUP WIZARD
# ============================================================
def full_setup():
    """Run the complete setup wizard."""
    print_banner()

    print(f"{Colors.BOLD}Kya karna hai?{Colors.END}")
    print()
    print("  1. 🔧 Generate Config (Firebase + Cloudinary)")
    print("  2. 🔐 Generate Firestore Rules")
    print("  3. ✅ Validate Config")
    print("  4. 🚀 Deploy to Vercel (Preview)")
    print("  5. 🌐 Deploy to Vercel (Production)")
    print("  6. 📦 Full Setup (Config + Rules + Deploy)")
    print("  7. ❌ Exit")
    print()

    choice = input(f"{Colors.CYAN}Choice (1-7): {Colors.END}").strip()

    if choice == "1":
        generate_config()
    elif choice == "2":
        generate_all_rules()
    elif choice == "3":
        validate_config()
    elif choice == "4":
        deploy_to_vercel(production=False)
    elif choice == "5":
        deploy_to_vercel(production=True)
    elif choice == "6":
        if generate_config():
            generate_all_rules()
            print()
            response = input(f"{Colors.CYAN}Vercel pe deploy kare? (y/N): {Colors.END}").strip().lower()
            if response == 'y':
                deploy_to_vercel(production=True)
    elif choice == "7":
        print_info("Bye! 👋")
        sys.exit(0)
    else:
        print_error("Invalid choice (1-7 enter karo)")


# ============================================================
# CLI ARGUMENTS
# ============================================================
def main():
    if len(sys.argv) > 1:
        arg = sys.argv[1]
        print_banner()

        if arg in ("--generate-config", "-c"):
            generate_config()
        elif arg in ("--generate-rules", "-r"):
            generate_all_rules()
        elif arg in ("--validate", "-v"):
            validate_config()
        elif arg in ("--deploy", "-d"):
            deploy_to_vercel(production=True)
        elif arg in ("--deploy-preview", "-p"):
            deploy_to_vercel(production=False)
        elif arg in ("--help", "-h"):
            print(f"{Colors.BOLD}Available Commands:{Colors.END}")
            print()
            print(f"  {Colors.CYAN}python setup_firebase.py{Colors.END}                Interactive wizard")
            print(f"  {Colors.CYAN}python setup_firebase.py --generate-config{Colors.END}  Firebase + Cloudinary config")
            print(f"  {Colors.CYAN}python setup_firebase.py --generate-rules{Colors.END}   Firestore security rules")
            print(f"  {Colors.CYAN}python setup_firebase.py --validate{Colors.END}         Validate config")
            print(f"  {Colors.CYAN}python setup_firebase.py --deploy{Colors.END}           Deploy to Vercel (prod)")
            print(f"  {Colors.CYAN}python setup_firebase.py --deploy-preview{Colors.END}   Deploy to Vercel (preview)")
            print()
            print(f"  Short flags: {Colors.CYAN}-c, -r, -v, -d, -p, -h{Colors.END}")
            print()
            print(f"{Colors.BOLD}Services Used (ALL FREE):{Colors.END}")
            print(f"  • Firebase Auth     — Unlimited users")
            print(f"  • Firebase Firestore — 1GB free")
            print(f"  • Cloudinary        — 25GB storage free")
            print(f"  • Vercel            — 100GB bandwidth free")
        else:
            print_error(f"Unknown: {arg}")
            print_info("Use --help for commands")
    else:
        full_setup()


if __name__ == "__main__":
    main()
